package com.example.testsdk

enum class SdkActivityEvents(val nameEvent: String) {
    EVENT_CREATED("ACTIVITY_CREATED"),
    EVENT_STARTED("ACTIVITY_STARTED"),
    EVENT_RESUMED("ACTIVITY_RESUMED"),
    EVENT_PAUSED("ACTIVITY_PAUSED"),
    EVENT_STOPPED("ACTIVITY_STOPPED"),
    EVENT_SAVE_STATE("ACTIVITY_SAVE_INSTANCE_STATE"),
    EVENT_DESTROYED("ACTIVITY_DESTROYED")
}

enum class SdkFragmentEvents(val nameEvent: String) {
    EVENT_CREATED("FRAGMENT_CREATED"),
    EVENT_VIEW_CREATED("FRAGMENT_VIEW_CREATED"),
    EVENT_STOPPED("FRAGMENT_STOPPED"),
    EVENT_RESUMED("FRAGMENT_RESUMED"),
    EVENT_ATTACHED("FRAGMENT_ATTACHED"),
    EVENT_PRE_ATTACHED("FRAGMENT_PRE_ATTACHED"),
    EVENT_DESTROYED("FRAGMENT_DESTROYED"),
    EVENT_SAVE_STATE("FRAGMENT_SAVE_INSTANCE_STATE"),
    EVENT_STARTED("FRAGMENT_STARTED"),
    EVENT_VIEW_DESTROYED("FRAGMENT_DESTROYED"),
    EVENT_PRE_CREATED("FRAGMENT_PRE_CREATED"),
    EVENT_ACTIVITY_CREATED("FRAGMENT_ACTIVITY_CREATED"),
    EVENT_PAUSED("FRAGMENT_PAUSED"),
    EVENT_DETACHED("FRAGMENT_DETACHED"),
}

const val TAG_ANALYTICS = "TEST_SDK"